-- Carrier GreenON: 사용자별 데이터와 원자적 포인트 처리를 위한 초기 스키마
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, green_points integer not null default 1000 check (green_points >= 0), green_level text not null default 'SEED' check (green_level in ('SEED','SPROUT','TREE')), created_at timestamptz not null default now());
create table public.missions (id text primary key, title text not null, description text not null, reward_points integer not null check(reward_points>0), target_minutes integer not null check(target_minutes>0), is_active boolean not null default true);
create table public.user_missions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, mission_id text not null references public.missions(id), mission_date date not null default current_date, status text not null default 'active' check(status in ('active','completed','failed')), progress_minutes integer not null default 0, rewarded_at timestamptz, created_at timestamptz not null default now(), unique(user_id,mission_id,mission_date));
create table public.point_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, amount integer not null check(amount<>0), type text not null check(type in ('earn','spend')), description text not null, reference_id uuid, created_at timestamptz not null default now());
create table public.rewards (id text primary key, category text not null check(category in ('FOOD','LIFE','CARRIER')), name text not null, description text not null default '', points integer not null check(points>0), emoji text not null default '🎁', stock integer not null default 999 check(stock>=0), is_active boolean not null default true);
create table public.reward_orders (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, reward_id text not null references public.rewards(id), points_spent integer not null check(points_spent>0), created_at timestamptz not null default now());
create table public.aircon_status (user_id uuid primary key references public.profiles(id) on delete cascade, power boolean not null default true, mode text not null default 'COOL', temperature integer not null default 26 check(temperature between 18 and 30), fan text not null default 'AUTO', minutes integer not null default 0, filter integer not null default 100 check(filter between 0 and 100), sensor_ok boolean not null default true, updated_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.missions enable row level security; alter table public.user_missions enable row level security; alter table public.point_transactions enable row level security; alter table public.rewards enable row level security; alter table public.reward_orders enable row level security; alter table public.aircon_status enable row level security;
create policy "own profile read" on public.profiles for select to authenticated using ((select auth.uid())=id);
create policy "mission catalog read" on public.missions for select to authenticated using (is_active);
create policy "own missions read" on public.user_missions for select to authenticated using ((select auth.uid())=user_id);
create policy "own points read" on public.point_transactions for select to authenticated using ((select auth.uid())=user_id);
create policy "reward catalog read" on public.rewards for select to authenticated using (is_active);
create policy "own orders read" on public.reward_orders for select to authenticated using ((select auth.uid())=user_id);
create policy "own aircon read" on public.aircon_status for select to authenticated using ((select auth.uid())=user_id);
create policy "own aircon update" on public.aircon_status for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
grant select on public.profiles,public.missions,public.user_missions,public.point_transactions,public.rewards,public.reward_orders,public.aircon_status to authenticated;
grant update on public.aircon_status to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,email) values(new.id,new.email); insert into public.aircon_status(user_id) values(new.id); insert into public.point_transactions(user_id,amount,type,description) values(new.id,1000,'earn','GreenON 시작 선물'); return new; end $$;
revoke execute on function public.handle_new_user() from public,anon,authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.start_daily_mission(p_mission_id text) returns void language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then raise exception '로그인이 필요합니다'; end if; insert into public.user_missions(user_id,mission_id) values(auth.uid(),p_mission_id) on conflict(user_id,mission_id,mission_date) do nothing; end $$;
create or replace function public.advance_aircon_mission(p_minutes integer) returns void language plpgsql security definer set search_path='' as $$ declare m public.user_missions; a public.aircon_status; reward integer; begin if auth.uid() is null or p_minutes<>30 then raise exception '잘못된 요청입니다'; end if; select * into a from public.aircon_status where user_id=auth.uid(); if not a.power or a.temperature<26 or a.filter<20 or not a.sensor_ok then raise exception '미션 조건을 확인해 주세요'; end if; select * into m from public.user_missions where user_id=auth.uid() and mission_date=current_date and status='active' for update; if m.id is null then raise exception '진행 중인 미션이 없습니다'; end if; update public.user_missions set progress_minutes=least(progress_minutes+p_minutes,120) where id=m.id returning * into m; update public.aircon_status set minutes=minutes+p_minutes,updated_at=now() where user_id=auth.uid(); if m.progress_minutes>=120 and m.rewarded_at is null then select reward_points into reward from public.missions where id=m.mission_id; update public.user_missions set status='completed',rewarded_at=now() where id=m.id; update public.profiles set green_points=green_points+reward,green_level=case when green_points+reward>=5000 then 'TREE' when green_points+reward>=2000 then 'SPROUT' else 'SEED' end where id=auth.uid(); insert into public.point_transactions(user_id,amount,type,description,reference_id) values(auth.uid(),reward,'earn','26°C 친환경 냉방 미션',m.id); end if; end $$;
create or replace function public.purchase_reward(p_reward_id text) returns void language plpgsql security definer set search_path='' as $$ declare price integer; order_id uuid; begin if auth.uid() is null then raise exception '로그인이 필요합니다'; end if; select points into price from public.rewards where id=p_reward_id and is_active and stock>0 for update; if price is null then raise exception '구매할 수 없는 상품입니다'; end if; update public.profiles set green_points=green_points-price,green_level=case when green_points-price>=5000 then 'TREE' when green_points-price>=2000 then 'SPROUT' else 'SEED' end where id=auth.uid() and green_points>=price; if not found then raise exception 'GREEN POINT가 부족합니다'; end if; insert into public.reward_orders(user_id,reward_id,points_spent) values(auth.uid(),p_reward_id,price) returning id into order_id; update public.rewards set stock=stock-1 where id=p_reward_id; insert into public.point_transactions(user_id,amount,type,description,reference_id) select auth.uid(),-price,'spend',name||' 구매',order_id from public.rewards where id=p_reward_id; end $$;
revoke execute on function public.start_daily_mission(text),public.advance_aircon_mission(integer),public.purchase_reward(text) from public,anon;
grant execute on function public.start_daily_mission(text),public.advance_aircon_mission(integer),public.purchase_reward(text) to authenticated;
insert into public.missions values('eco-26','26°C로 2시간 시원하게','냉방 모드에서 설정 온도 26°C 이상을 유지해요.',300,120,true) on conflict do nothing;
insert into public.rewards(id,category,name,description,points,emoji) values ('coffee','FOOD','아이스 아메리카노','시원한 친환경 휴식',1200,'🥤'),('tumbler','LIFE','GreenON 텀블러','일회용 컵을 줄여요',3200,'🌱'),('filter','CARRIER','에어컨 필터 쿠폰','깨끗한 바람을 위한 쿠폰',5000,'❄️') on conflict do nothing;
